version: 2
jobs:
  build:
    working_directory: ~/dev-portal
    docker:
      - image: circleci/node:6.10.3
      - image: circleci/mongo:3.4.4
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: /tmp/logs
          destination: logs
    
    